name: Run tests on PR
on: issue_comment

jobs:
  pr_commented:
    name: Run Tests for PR
    runs-on: ubuntu-latest
    steps:
      - name: Check association
        run: |
          if [[ -z "${{ github.event.issue.pull_request }}" ]]
          then
            exit 1
          fi
          if ! [[ ${{ github.event.comment.body }} =~ .*/run tests .* ]]
          then
            exit 1
          fi
          allowed=("OWNER" "COLLABORATOR")
          value="\<${{ github.event.issue.author_association }}\>"
        
          if [[ ${array[@]} =~ $value ]]
          then
            exit 0
          else
            exit 1
          fi
