on:
  workflow_run:
    workflows: [Run Tests on PR]
    types:
      - completed

  workflow_call:
    inputs:
      pr:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: echo test
      run: |
        echo "This is a test"

    - name: Checkout
      uses: actions/checkout@v4

    - name: Switch branch
      if: inputs.pr
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        sudo apt-get update
        sudo apt-get install -y hub
        hub pr checkout ${{ inputs.pr }}
        echo "sha=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: echo PR
      run: |
        cat .github/workflows/test.yml

    - name: Set final commit status
      if: inputs.pr && always()
      uses: myrotvorets/set-commit-status-action@v2.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}
        context: Tests
        sha: ${{ env.sha }}
  
