on:
  workflow_call:
    inputs:
      pr:
        required: true
        type: string

jobs:
  test:
    name: This is a test
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: echo test
      run: |
        echo "This is a test"
        echo "${{ env.job_name }}"
        set
        
  test2:
    permissions:
      contents: write
      packages: write
      checks: write
    if: github.event_name == 'issue_comment'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Switch branch
      if: inputs.pr
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        sudo apt-get update
        sudo apt-get install -y hub
        hub pr checkout ${{ inputs.pr }}
        echo "sha=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: echo PR
      run: |
        cat .github/workflows/test.yml

    - name: Get Current Job Log URL
      if: inputs.pr && always()
      uses: Tiryoh/gha-jobid-action@v1
      id: jobs
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        job_name: "Run Tests / test2"

    - name: Set final commit status
      if: inputs.pr && always()
      uses: myrotvorets/set-commit-status-action@v2.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}
        context: ${{ github.jobs[github.job].name }}
        sha: ${{ env.sha }}
        targetUrl: ${{ steps.jobs.outputs.html_url }}
  
