on:
  workflow_run:
    workflows: [Run Tests on PR]
    types:
      - completed

  workflow_call:
    inputs:
      pr:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: echo test
      run: |
        echo "This is a test 2"
        echo "This is a test"

    - name: Checkout
      uses: actions/checkout@v4

    - name: Switch branch
      if: inputs.pr
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        sudo apt-get update
        sudo apt-get install -y hub
        hub pr checkout ${{ inputs.pr }}

    - name: echo PR
      run: |
        cat .github/workflows/test.yml
   
