on:
  workflow_run:
    workflows: [Run Tests on PR]
    types:
      - completed

jobs:
  test:
    if: >
      github.event_name == 'push' ||
      ( github.event.workflow_run.event == 'pull_request' &&
        github.event.workflow_run.conclusion == 'success' )
    runs-on: ubuntu-latest
    steps:
    - name: echo test
      run: |
        echo "This is a test"
    
